// Woordenbank De Letterdief — gecontroleerd door tests/check_words.py en tests/game.test.mjs
// w = woord, g = klankletters, e = plaatje (Unicode ≤ 13), nz = posities die niet klinken zoals geschreven
// (eind-d als t, eind-b als p, w in "auw") — die mag Snaai nooit stelen en zulke woorden worden niet gelezen/gespeld.
// Bewust weggelaten: paren met bijna gelijke plaatjes (kip/haan, muis/rat, trein/tram, boot/schip, mug/vlieg).
export const WORDS = [
  // wereld 1 (m s i k p aa r e v)
  { w: 'vis', g: ['v', 'i', 's'], e: '🐟' },
  { w: 'kip', g: ['k', 'i', 'p'], e: '🐔' },
  { w: 'aap', g: ['aa', 'p'], e: '🐵' },
  { w: 'raam', g: ['r', 'aa', 'm'], e: '🪟' },
  { w: 'kaas', g: ['k', 'aa', 's'], e: '🧀' },
  { w: 'spek', g: ['s', 'p', 'e', 'k'], e: '🥓' },
  { w: 'kaars', g: ['k', 'aa', 'r', 's'], e: '🕯️' },
  { w: 'kers', g: ['k', 'e', 'r', 's'], e: '🍒' },
  // wereld 2 (+ n t ee b oo)
  { w: 'maan', g: ['m', 'aa', 'n'], e: '🌙' },
  { w: 'roos', g: ['r', 'oo', 's'], e: '🌹' },
  { w: 'boom', g: ['b', 'oo', 'm'], e: '🌳' },
  { w: 'peer', g: ['p', 'ee', 'r'], e: '🍐' },
  { w: 'been', g: ['b', 'ee', 'n'], e: '🦴' },
  { w: 'net', g: ['n', 'e', 't'], e: '🥅' },
  { w: 'pen', g: ['p', 'e', 'n'], e: '🖊️' },
  { w: 'tent', g: ['t', 'e', 'n', 't'], e: '⛺' },
  { w: 'noot', g: ['n', 'oo', 't'], e: '🌰' },
  { w: 'beer', g: ['b', 'ee', 'r'], e: '🐻' },
  { w: 'pet', g: ['p', 'e', 't'], e: '🧢' },
  { w: 'ster', g: ['s', 't', 'e', 'r'], e: '⭐' },
  { w: 'oor', g: ['oo', 'r'], e: '👂' },
  { w: 'taart', g: ['t', 'aa', 'r', 't'], e: '🎂' },
  { w: 'kroon', g: ['k', 'r', 'oo', 'n'], e: '👑' },
  { w: 'prins', g: ['p', 'r', 'i', 'n', 's'], e: '🤴' },
  { w: 'prinses', g: ['p', 'r', 'i', 'n', 's', 'e', 's'], e: '👸' },
  { w: 'kerk', g: ['k', 'e', 'r', 'k'], e: '⛪' },
  { w: 'kaart', g: ['k', 'aa', 'r', 't'], e: '🗺️' },
  { w: 'kraan', g: ['k', 'r', 'aa', 'n'], e: '🚰' },
  // wereld 3 (+ d oe z ij h)
  { w: 'doos', g: ['d', 'oo', 's'], e: '📦' },
  { w: 'poes', g: ['p', 'oe', 's'], e: '🐱' },
  { w: 'koe', g: ['k', 'oe'], e: '🐄' },
  { w: 'ijs', g: ['ij', 's'], e: '🍦' },
  { w: 'zeep', g: ['z', 'ee', 'p'], e: '🧼' },
  { w: 'prijs', g: ['p', 'r', 'ij', 's'], e: '🏆' },
  { w: 'bij', g: ['b', 'ij'], e: '🐝' },
  { w: 'boek', g: ['b', 'oe', 'k'], e: '📖' },
  { w: 'koek', g: ['k', 'oe', 'k'], e: '🍪' },
  { w: 'soep', g: ['s', 'oe', 'p'], e: '🍲' },
  { w: 'snoep', g: ['s', 'n', 'oe', 'p'], e: '🍬' },
  { w: 'zee', g: ['z', 'ee'], e: '🌊' },
  { w: 'hert', g: ['h', 'e', 'r', 't'], e: '🦌' },
  { w: 'rijst', g: ['r', 'ij', 's', 't'], e: '🍚' },
  { w: 'voet', g: ['v', 'oe', 't'], e: '🦶' },
  { w: 'boer', g: ['b', 'oe', 'r'], e: '👨‍🌾' },
  { w: 'krijt', g: ['k', 'r', 'ij', 't'], e: '🖍️' },
  { w: 'haas', g: ['h', 'aa', 's'], e: '🐇' },
  { w: 'draak', g: ['d', 'r', 'aa', 'k'], e: '🐉' },
  { w: 'zes', g: ['z', 'e', 's'], e: '6️⃣' },
  { w: 'hoed', g: ['h', 'oe', 'd'], e: '🎩', nz: [2] },
  { w: 'bed', g: ['b', 'e', 'd'], e: '🛏️', nz: [2] },
  { w: 'brood', g: ['b', 'r', 'oo', 'd'], e: '🍞', nz: [3] },
  // wereld 4 (+ w o a u j)
  { w: 'zon', g: ['z', 'o', 'n'], e: '☀️' },
  { w: 'bus', g: ['b', 'u', 's'], e: '🚌' },
  { w: 'pop', g: ['p', 'o', 'p'], e: '🪆' },
  { w: 'sok', g: ['s', 'o', 'k'], e: '🧦' },
  { w: 'jas', g: ['j', 'a', 's'], e: '🧥' },
  { w: 'pan', g: ['p', 'a', 'n'], e: '🍳' },
  { w: 'sap', g: ['s', 'a', 'p'], e: '🧃' },
  { w: 'mok', g: ['m', 'o', 'k'], e: '☕' },
  { w: 'rups', g: ['r', 'u', 'p', 's'], e: '🐛' },
  { w: 'vos', g: ['v', 'o', 's'], e: '🦊' },
  { w: 'das', g: ['d', 'a', 's'], e: '🧣' },
  { w: 'tas', g: ['t', 'a', 's'], e: '👜' },
  { w: 'kus', g: ['k', 'u', 's'], e: '💋' },
  { w: 'step', g: ['s', 't', 'e', 'p'], e: '🛴' },
  { w: 'jurk', g: ['j', 'u', 'r', 'k'], e: '👗' },
  { w: 'worm', g: ['w', 'o', 'r', 'm'], e: '🪱' },
  { w: 'kom', g: ['k', 'o', 'm'], e: '🥣' },
  { w: 'kok', g: ['k', 'o', 'k'], e: '🧑‍🍳' },
  { w: 'vork', g: ['v', 'o', 'r', 'k'], e: '🍴' },
  { w: 'zwaan', g: ['z', 'w', 'aa', 'n'], e: '🦢' },
  { w: 'munt', g: ['m', 'u', 'n', 't'], e: '🪙' },
  { w: 'trap', g: ['t', 'r', 'a', 'p'], e: '🪜' },
  { w: 'want', g: ['w', 'a', 'n', 't'], e: '🧤' },
  { w: 'trom', g: ['t', 'r', 'o', 'm'], e: '🥁' },
  { w: 'twee', g: ['t', 'w', 'ee'], e: '2️⃣' },
  { w: 'hart', g: ['h', 'a', 'r', 't'], e: '❤️' },
  { w: 'arm', g: ['a', 'r', 'm'], e: '💪' },
  { w: 'spons', g: ['s', 'p', 'o', 'n', 's'], e: '🧽' },
  { w: 'hond', g: ['h', 'o', 'n', 'd'], e: '🐶', nz: [3] },
  { w: 'mond', g: ['m', 'o', 'n', 'd'], e: '👄', nz: [3] },
  { w: 'hand', g: ['h', 'a', 'n', 'd'], e: '✋', nz: [3] },
  { w: 'mand', g: ['m', 'a', 'n', 'd'], e: '🧺', nz: [3] },
  { w: 'web', g: ['w', 'e', 'b'], e: '🕸️', nz: [2] },
  { w: 'wind', g: ['w', 'i', 'n', 'd'], e: '🌬️', nz: [3] },
  { w: 'kind', g: ['k', 'i', 'n', 'd'], e: '🧒', nz: [3] },
  { w: 'bord', g: ['b', 'o', 'r', 'd'], e: '🍽️', nz: [3] },
  { w: 'zeehond', g: ['z', 'ee', 'h', 'o', 'n', 'd'], e: '🦭', nz: [5] },
  { w: 'krab', g: ['k', 'r', 'a', 'b'], e: '🦀', nz: [3] },
  { w: 'bad', g: ['b', 'a', 'd'], e: '🛁', nz: [2] },
  { w: 'paard', g: ['p', 'aa', 'r', 'd'], e: '🐴', nz: [3] },
  { w: 'eend', g: ['ee', 'n', 'd'], e: '🦆', nz: [2] },
  { w: 'tand', g: ['t', 'a', 'n', 'd'], e: '🦷', nz: [3] },
  { w: 'strand', g: ['s', 't', 'r', 'a', 'n', 'd'], e: '🏖️', nz: [5] },
  // wereld 5 (+ eu ie l ou uu)
  { w: 'neus', g: ['n', 'eu', 's'], e: '👃' },
  { w: 'deur', g: ['d', 'eu', 'r'], e: '🚪' },
  { w: 'kleur', g: ['k', 'l', 'eu', 'r'], e: '🎨' },
  { w: 'vier', g: ['v', 'ie', 'r'], e: '4️⃣' },
  { w: 'mier', g: ['m', 'ie', 'r'], e: '🐜' },
  { w: 'tien', g: ['t', 'ie', 'n'], e: '🔟' },
  { w: 'drie', g: ['d', 'r', 'ie'], e: '3️⃣' },
  { w: 'bril', g: ['b', 'r', 'i', 'l'], e: '👓' },
  { w: 'bal', g: ['b', 'a', 'l'], e: '⚽' },
  { w: 'vuur', g: ['v', 'uu', 'r'], e: '🔥' },
  { w: 'muur', g: ['m', 'uu', 'r'], e: '🧱' },
  { w: 'vuurwerk', g: ['v', 'uu', 'r', 'w', 'e', 'r', 'k'], e: '🎆' },
  { w: 'hout', g: ['h', 'ou', 't'], e: '🪵' },
  { w: 'zout', g: ['z', 'ou', 't'], e: '🧂' },
  { w: 'bout', g: ['b', 'ou', 't'], e: '🔩' },
  { w: 'goud', g: ['g', 'ou', 'd'], e: '🥇', nz: [2] },
  { w: 'koud', g: ['k', 'ou', 'd'], e: '🥶', nz: [2] },
  { w: 'lamp', g: ['l', 'a', 'm', 'p'], e: '💡' },
  { w: 'bel', g: ['b', 'e', 'l'], e: '🔔' },
  { w: 'wol', g: ['w', 'o', 'l'], e: '🧶' },
  { w: 'slak', g: ['s', 'l', 'a', 'k'], e: '🐌' },
  { w: 'melk', g: ['m', 'e', 'l', 'k'], e: '🥛' },
  { w: 'tulp', g: ['t', 'u', 'l', 'p'], e: '🌷' },
  { w: 'klok', g: ['k', 'l', 'o', 'k'], e: '🕰️' },
  { w: 'stoel', g: ['s', 't', 'oe', 'l'], e: '🪑' },
  { w: 'vulkaan', g: ['v', 'u', 'l', 'k', 'aa', 'n'], e: '🌋' },
  { w: 'slee', g: ['s', 'l', 'ee'], e: '🛷' },
  { w: 'wolk', g: ['w', 'o', 'l', 'k'], e: '☁️' },
  { w: 'walvis', g: ['w', 'a', 'l', 'v', 'i', 's'], e: '🐳' },
  { w: 'kasteel', g: ['k', 'a', 's', 't', 'ee', 'l'], e: '🏰' },
  { w: 'helm', g: ['h', 'e', 'l', 'm'], e: '⛑️' },
  { w: 'laars', g: ['l', 'aa', 'r', 's'], e: '👢' },
  { w: 'blad', g: ['b', 'l', 'a', 'd'], e: '🍃', nz: [3] },
  // wereld 6 (+ g au ui f ei)
  { w: 'geit', g: ['g', 'ei', 't'], e: '🐐' },
  { w: 'uil', g: ['ui', 'l'], e: '🦉' },
  { w: 'pauw', g: ['p', 'au', 'w'], e: '🦚', nz: [2] },
  { w: 'duif', g: ['d', 'ui', 'f'], e: '🕊️' },
  { w: 'ei', g: ['ei'], e: '🥚' },
  { w: 'huis', g: ['h', 'ui', 's'], e: '🏠' },
  { w: 'muis', g: ['m', 'ui', 's'], e: '🐭' },
  { w: 'fiets', g: ['f', 'ie', 't', 's'], e: '🚲' },
  { w: 'vlag', g: ['v', 'l', 'a', 'g'], e: '🚩' },
  { w: 'oog', g: ['oo', 'g'], e: '👁️' },
  { w: 'berg', g: ['b', 'e', 'r', 'g'], e: '⛰️' },
  { w: 'trein', g: ['t', 'r', 'ei', 'n'], e: '🚂' },
  { w: 'duim', g: ['d', 'ui', 'm'], e: '👍' },
  { w: 'mug', g: ['m', 'u', 'g'], e: '🦟' },
  { w: 'brug', g: ['b', 'r', 'u', 'g'], e: '🌉' },
  { w: 'fee', g: ['f', 'ee'], e: '🧚' },
  { w: 'wolf', g: ['w', 'o', 'l', 'f'], e: '🐺' },
  { w: 'juf', g: ['j', 'u', 'f'], e: '👩‍🏫' },
  { w: 'brief', g: ['b', 'r', 'ie', 'f'], e: '✉️' },
  { w: 'lift', g: ['l', 'i', 'f', 't'], e: '🛗' },
  { w: 'zaag', g: ['z', 'aa', 'g'], e: '🪚' },
  { w: 'augurk', g: ['au', 'g', 'u', 'r', 'k'], e: '🥒' },
  { w: 'saus', g: ['s', 'au', 's'], e: '🥫' },
  { w: 'druif', g: ['d', 'r', 'ui', 'f'], e: '🍇' },
  { w: 'ui', g: ['ui'], e: '🧅' },
  { w: 'friet', g: ['f', 'r', 'ie', 't'], e: '🍟' },
  { w: 'vijf', g: ['v', 'ij', 'f'], e: '5️⃣' },
  { w: 'feest', g: ['f', 'ee', 's', 't'], e: '🎉' },
  { w: 'duikbril', g: ['d', 'ui', 'k', 'b', 'r', 'i', 'l'], e: '🤿' },
  { w: 'dief', g: ['d', 'ie', 'f'], e: '🦹' },
  { w: 'fles', g: ['f', 'l', 'e', 's'], e: '🍼' },
  { w: 'zeil', g: ['z', 'ei', 'l'], e: '⛵' },
  { w: 'geld', g: ['g', 'e', 'l', 'd'], e: '💶', nz: [3] },
  { w: 'eiland', g: ['ei', 'l', 'a', 'n', 'd'], e: '🏝️', nz: [4] },
  // wereld 7 (+ sch ng nk ch)
  { w: 'ring', g: ['r', 'i', 'ng'], e: '💍' },
  { w: 'schip', g: ['sch', 'i', 'p'], e: '🚢' },
  { w: 'bank', g: ['b', 'a', 'nk'], e: '🛋️' },
  { w: 'slang', g: ['s', 'l', 'a', 'ng'], e: '🐍' },
  { w: 'schaap', g: ['sch', 'aa', 'p'], e: '🐑' },
  { w: 'school', g: ['sch', 'oo', 'l'], e: '🏫' },
  { w: 'schoen', g: ['sch', 'oe', 'n'], e: '👟' },
  { w: 'tong', g: ['t', 'o', 'ng'], e: '👅' },
  { w: 'schaar', g: ['sch', 'aa', 'r'], e: '✂️' },
  { w: 'schelp', g: ['sch', 'e', 'l', 'p'], e: '🐚' },
  { w: 'nacht', g: ['n', 'a', 'ch', 't'], e: '🌃' },
  { w: 'acht', g: ['a', 'ch', 't'], e: '8️⃣' },
  { w: 'lach', g: ['l', 'a', 'ch'], e: '😄' },
  { w: 'stinkdier', g: ['s', 't', 'i', 'nk', 'd', 'ie', 'r'], e: '🦨' },
  { w: 'inktvis', g: ['i', 'nk', 't', 'v', 'i', 's'], e: '🦑' },
  { w: 'schaats', g: ['sch', 'aa', 't', 's'], e: '⛸️' },
  { w: 'hangslot', g: ['h', 'a', 'ng', 's', 'l', 'o', 't'], e: '🔒' },
  { w: 'schildpad', g: ['sch', 'i', 'l', 'd', 'p', 'a', 'd'], e: '🐢', nz: [3, 6] },
  { w: 'schild', g: ['sch', 'i', 'l', 'd'], e: '🛡️', nz: [3] },
];

// Sleutelwoord per klank ("dit is de mmm van maan"), zoveel mogelijk de VLL-woorden.
export const KEYWORDS = {
  i: 'vis', k: 'kip', m: 'maan', s: 'sok', p: 'pen', aa: 'aap', r: 'roos', e: 'pen', v: 'vis',
  n: 'neus', t: 'tent', ee: 'peer', b: 'boom', oo: 'oog', d: 'doos', oe: 'poes', z: 'zeep', ij: 'ijs', h: 'huis',
  w: 'worm', o: 'pop', a: 'jas', u: 'bus', j: 'jas', eu: 'neus', ie: 'mier', l: 'lamp', ou: 'hout', uu: 'vuur',
  g: 'geit', au: 'pauw', ui: 'uil', f: 'fiets', ei: 'ei', sch: 'schip', ng: 'ring', nk: 'bank', ch: 'nacht',
};
